/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author Personal
 */
public class Frmlogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frmlogin.class.getName());

    /**
     * Creates new form Frmlogin
     */
    public Frmlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        HopVertical = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JPanel();
        HopHorizontal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(146, 200, 141));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HopVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Vertical-java.png"))); // NOI18N
        Background.add(HopVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 390, 620));

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HopHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Horizontal-Java.png"))); // NOI18N
        FondoBlanco.add(HopHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 59, 89));
        jLabel1.setText("Por favor inserte sus datos");
        jLabel1.setToolTipText("");
        FondoBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 240, 40));

        jLabel3.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 42)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 59, 89));
        jLabel3.setText("Bienvenido");
        jLabel3.setToolTipText("");
        FondoBlanco.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 270, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 59, 89));
        jLabel4.setText("Contraseña");
        jLabel4.setToolTipText("");
        FondoBlanco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 120, 40));

        jLabel5.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(35, 59, 89));
        jLabel5.setText("Correo electrónico");
        jLabel5.setToolTipText("");
        FondoBlanco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 200, 40));

        jTextField1.setBackground(new java.awt.Color(11, 101, 121));
        FondoBlanco.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 190, 30));

        jTextField2.setBackground(new java.awt.Color(11, 101, 121));
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        FondoBlanco.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 190, 30));

        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frmlogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel HopHorizontal;
    private javax.swing.JLabel HopVertical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
