/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import clases.ClsGlobales;
import db.UsuarioDAO;
import entidades.Usuario;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Personal
 */
public class Frmlogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frmlogin.class.getName());

    /**
     * Creates new form Frmlogin
     */
    public Frmlogin() {
        initComponents();
        
        //Poner imagen (icono de HOP [marca de mi proyecto] en la ventana al iniciar 
        //Codigo visto de Tutorial de Youtube ya que para acabados de mejor presentacion quise investigar
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/HOP_1.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        HopVertical = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JPanel();
        FondoBlanco1 = new javax.swing.JPanel();
        HopHorizontal = new javax.swing.JLabel();
        HopHorizontal1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnIngresoSistema = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        intRegistrese = new javax.swing.JLabel();
        intOlvidoCLave = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INICIO SESIÓN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(146, 200, 141));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HopVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Vertical-java.png"))); // NOI18N
        Background.add(HopVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 390, 620));

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBlanco1.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HopHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Horizontal-Java.png"))); // NOI18N
        FondoBlanco1.add(HopHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        HopHorizontal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Horizontal-Java.png"))); // NOI18N
        FondoBlanco1.add(HopHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 59, 89));
        jLabel9.setText("Contraseña");
        jLabel9.setToolTipText("");
        FondoBlanco1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, 40));

        txtCorreo.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(35, 59, 89));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        FondoBlanco1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 220, 30));

        btnIngresoSistema.setBackground(new java.awt.Color(105, 191, 165));
        btnIngresoSistema.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 18)); // NOI18N
        btnIngresoSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresoSistema.setText("INICIAR SESIÓN");
        btnIngresoSistema.setBorder(null);
        btnIngresoSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoSistemaActionPerformed(evt);
            }
        });
        FondoBlanco1.add(btnIngresoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 220, 50));

        jLabel11.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(35, 59, 89));
        jLabel11.setText("Correo electrónico");
        jLabel11.setToolTipText("");
        FondoBlanco1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 40));

        jLabel12.setFont(new java.awt.Font("Baloo 2 Medium", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(35, 59, 89));
        jLabel12.setText("¿Primera vez?");
        jLabel12.setToolTipText("");
        FondoBlanco1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 110, 40));

        intRegistrese.setFont(new java.awt.Font("Baloo 2 Medium", 1, 18)); // NOI18N
        intRegistrese.setForeground(new java.awt.Color(0, 0, 204));
        intRegistrese.setText("Registrese aquí");
        intRegistrese.setToolTipText("");
        intRegistrese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        intRegistrese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intRegistreseMouseClicked(evt);
            }
        });
        FondoBlanco1.add(intRegistrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 130, 40));

        intOlvidoCLave.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 16)); // NOI18N
        intOlvidoCLave.setForeground(new java.awt.Color(0, 0, 204));
        intOlvidoCLave.setText("¿Olvidó su contraseña?");
        intOlvidoCLave.setToolTipText("");
        intOlvidoCLave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        intOlvidoCLave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intOlvidoCLaveMouseClicked(evt);
            }
        });
        FondoBlanco1.add(intOlvidoCLave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, 40));
        FondoBlanco1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 220, 10));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 59, 89));
        jLabel1.setText("Por favor inserte sus datos");
        jLabel1.setToolTipText("");
        FondoBlanco1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 260, 40));

        jLabel3.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 59, 89));
        jLabel3.setText("Bienvenido");
        jLabel3.setToolTipText("");
        FondoBlanco1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 40));

        txtClave.setForeground(new java.awt.Color(35, 59, 89));
        txtClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClave.setText("jPasswordField1");
        txtClave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtClave.setCaretColor(new java.awt.Color(255, 255, 255));
        FondoBlanco1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 30));

        FondoBlanco.add(FondoBlanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 620));

        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void intRegistreseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intRegistreseMouseClicked
        // TODO add your handling code here:
        FrmRegistro fregistro = new FrmRegistro();
        fregistro.show();
        this.hide();
    }//GEN-LAST:event_intRegistreseMouseClicked

    private void btnIngresoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoSistemaActionPerformed
        // TODO add your handling code here:
        String correo = this.txtCorreo.getText();
        String clave = this.txtClave.getText();
        String claveTemp = FrmOlvidoC.generarContraseñaT();
        
        
        boolean validado = UsuarioDAO.validarAcceso(correo, clave);
        
        if (validado){
            ClsGlobales.fprincipal.show();
            this.hide();
        }
        
    }//GEN-LAST:event_btnIngresoSistemaActionPerformed

    private void intOlvidoCLaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intOlvidoCLaveMouseClicked
        // TODO add your handling code here:
        FrmOlvidoC folvidoContraseña = new FrmOlvidoC();
        folvidoContraseña.show();
        this.hide();
        
    }//GEN-LAST:event_intOlvidoCLaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frmlogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JPanel FondoBlanco1;
    private javax.swing.JLabel HopHorizontal;
    private javax.swing.JLabel HopHorizontal1;
    private javax.swing.JLabel HopVertical;
    private javax.swing.JButton btnIngresoSistema;
    private javax.swing.JLabel intOlvidoCLave;
    private javax.swing.JLabel intRegistrese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
