/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Clases.ClsEncriptar;
import clases.ClsGlobales;
import db.UsuarioDAO;
import entidades.Usuario;
import java.security.SecureRandom;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Personal
 */
public class FrmOlvidoC extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmOlvidoC.class.getName());

    /**
     * Creates new form FrmOlvidoC
     */
    public FrmOlvidoC() {
        initComponents();
        
        //Poner imagen (icono de HOP [marca de mi proyecto] en la ventana al iniciar 
        //Codigo visto de Tutorial de Youtube ya que para acabados de mejor presentacion quise investigar
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/HOP_1.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    //  FUNCIONES Y PROCEDIMIENTOS
    
    private String validarCampos(){
        String mensaje = "";
        String correo = this.txtCorreo.getText();
        
        
        
        
        
        
        if (correo.isEmpty()) {
            mensaje = "Los campos no pueden estar vacios";
        }
        
        
        
        return mensaje;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HopHorizontal1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HopHorizontal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Horizontal-Java.png"))); // NOI18N
        jPanel1.add(HopHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(35, 59, 89));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 220, 30));

        btnSalir.setBackground(new java.awt.Color(255, 0, 102));
        btnSalir.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 120, 50));

        jLabel11.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(35, 59, 89));
        jLabel11.setText("Correo electrónico");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 40));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 59, 89));
        jLabel1.setText("Por favor inserte sus datos");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 260, 40));

        jLabel3.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 59, 89));
        jLabel3.setText("Recuperación");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 50));

        btnRegistrar.setBackground(new java.awt.Color(35, 59, 89));
        btnRegistrar.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setToolTipText("");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       String correo = this.txtCorreo.getText();
        
        
        boolean validado = UsuarioDAO.validarAccesoC(correo);
        
        
        if (validado){
            JOptionPane.showMessageDialog(
                    null,
                    "Su contraseña temporal es:" + generarContraseñaT(),
                    "Contraseña Temporal",
                    JOptionPane.PLAIN_MESSAGE
                );
            
            ClsGlobales.fprincipal.show();
            this.hide();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    
            
            
            
    public static String generarContraseñaT() {
        final String CHARSET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        SecureRandom rnd = new SecureRandom();
        StringBuilder sb = new StringBuilder(6);
        for (int i = 0; i < 6; i++) {
            int index = rnd.nextInt(CHARSET.length());
            sb.append(CHARSET.charAt(index));
        }
        return sb.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmOlvidoC().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HopHorizontal1;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
