/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author Personal
 */
public class FrmRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistro.class.getName());

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        FondoBlanco1 = new javax.swing.JPanel();
        HopHorizontal = new javax.swing.JLabel();
        HopHorizontal1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnIngresoSistema = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtClave1 = new javax.swing.JTextField();
        btnIngresoSistema1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO");
        setResizable(false);

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBlanco1.setBackground(new java.awt.Color(105, 191, 165));
        FondoBlanco1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HopHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Horizontal-Java.png"))); // NOI18N
        FondoBlanco1.add(HopHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        HopHorizontal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Horizontal-Java.png"))); // NOI18N
        FondoBlanco1.add(HopHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contraseña");
        jLabel9.setToolTipText("");
        FondoBlanco1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, 40));

        txtClave.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtClave.setCaretColor(new java.awt.Color(255, 255, 255));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        FondoBlanco1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 30));

        txtCorreo.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(35, 59, 89));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        FondoBlanco1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 220, 30));

        btnIngresoSistema.setBackground(new java.awt.Color(255, 0, 102));
        btnIngresoSistema.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 18)); // NOI18N
        btnIngresoSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresoSistema.setText("SALIR");
        btnIngresoSistema.setBorder(null);
        btnIngresoSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FondoBlanco1.add(btnIngresoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 120, 50));

        jLabel11.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo electrónico");
        jLabel11.setToolTipText("");
        FondoBlanco1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 40));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Por favor inserte sus datos");
        jLabel1.setToolTipText("");
        FondoBlanco1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 260, 40));

        jLabel3.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro");
        jLabel3.setToolTipText("");
        FondoBlanco1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 50));

        jLabel10.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirme la contraseña");
        jLabel10.setToolTipText("");
        FondoBlanco1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 240, 40));

        txtClave1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtClave1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClave1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtClave1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtClave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClave1ActionPerformed(evt);
            }
        });
        FondoBlanco1.add(txtClave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 220, 30));

        btnIngresoSistema1.setBackground(new java.awt.Color(35, 59, 89));
        btnIngresoSistema1.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 18)); // NOI18N
        btnIngresoSistema1.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresoSistema1.setText("REGISTRAR");
        btnIngresoSistema1.setToolTipText("");
        btnIngresoSistema1.setBorder(null);
        btnIngresoSistema1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresoSistema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoSistema1ActionPerformed(evt);
            }
        });
        FondoBlanco1.add(btnIngresoSistema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 120, 50));

        FondoBlanco.add(FondoBlanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtClave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClave1ActionPerformed

    private void btnIngresoSistema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoSistema1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoSistema1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JPanel FondoBlanco1;
    private javax.swing.JLabel HopHorizontal;
    private javax.swing.JLabel HopHorizontal1;
    private javax.swing.JButton btnIngresoSistema;
    private javax.swing.JButton btnIngresoSistema1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtClave1;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
