/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Clases.ClsEncriptar;
import db.UsuarioDAO;
import entidades.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class FrmRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistro.class.getName());

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        initComponents();
        //Poner imagen (icono de HOP [marca de mi proyecto] en la ventana al iniciar 
        //Codigo visto de Tutorial de Youtube ya que para acabados de mejor presentacion quise investigar
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/HOP_1.png")).getImage());
    }

     //***************************
    
    //  FUNCIONES Y PROCEDIMIENTOS
    
    private String validarCampos(){
        String mensaje = "";
        String correo = this.txtCorreo.getText();
        String clave = this.txtClave.getText();
        String confclave = this.txtConfirmarClave.getText();
        
        if (clave.length() <6) {
            mensaje = " La clave debe ser mayor a 6 caracteres";
        }
        
        if (!clave.equals(confclave)) {
            mensaje = " Las contraseñas no son iguales";
        }
        
        if (correo.isEmpty() || clave.isEmpty() || confclave.isEmpty()) {
            mensaje = "Los campos no pueden estar vacios";
        }
        
        
        
        return mensaje;
    }
    
    //***************************
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBlanco = new javax.swing.JPanel();
        HopHorizontal1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();
        txtConfirmarClave = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBlanco.setBackground(new java.awt.Color(105, 191, 165));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HopHorizontal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hope-Horizontal-Java.png"))); // NOI18N
        FondoBlanco.add(HopHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contraseña");
        jLabel9.setToolTipText("");
        FondoBlanco.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 120, 40));

        txtCorreo.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(35, 59, 89));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        FondoBlanco.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 220, 30));

        btnSalir.setBackground(new java.awt.Color(255, 0, 102));
        btnSalir.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        FondoBlanco.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 120, 50));

        jLabel11.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo electrónico");
        jLabel11.setToolTipText("");
        FondoBlanco.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, 40));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 59, 89));
        jLabel1.setText("Por favor inserte sus datos");
        jLabel1.setToolTipText("");
        FondoBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 260, 40));

        jLabel3.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 59, 89));
        jLabel3.setText("Registro");
        jLabel3.setToolTipText("");
        FondoBlanco.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 50));

        jLabel10.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirme la contraseña");
        jLabel10.setToolTipText("");
        FondoBlanco.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 230, 40));

        btnRegistrar.setBackground(new java.awt.Color(35, 59, 89));
        btnRegistrar.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setToolTipText("");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        FondoBlanco.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 120, 50));

        txtClave.setForeground(new java.awt.Color(35, 59, 89));
        txtClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClave.setText("jPasswordField1");
        txtClave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        FondoBlanco.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 220, 30));

        txtConfirmarClave.setForeground(new java.awt.Color(35, 59, 89));
        txtConfirmarClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConfirmarClave.setText("jPasswordField1");
        txtConfirmarClave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtConfirmarClave.setCaretColor(new java.awt.Color(255, 255, 255));
        FondoBlanco.add(txtConfirmarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 220, 30));

        jLabel13.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Username / Nickgame");
        jLabel13.setToolTipText("");
        FondoBlanco.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 40));

        txtUsername.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(35, 59, 89));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        FondoBlanco.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 220, 30));

        jLabel14.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombre Completo");
        jLabel14.setToolTipText("");
        FondoBlanco.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, 40));

        txtNombreC.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtNombreC.setForeground(new java.awt.Color(35, 59, 89));
        txtNombreC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 59, 89), 2, true));
        txtNombreC.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCActionPerformed(evt);
            }
        });
        FondoBlanco.add(txtNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 220, 30));

        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 440, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Frmlogin flogin = new Frmlogin();
        flogin.show();
    }//GEN-LAST:event_formWindowClosed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String error = this.validarCampos();

        //Registrar
        if ( error.isEmpty()) {

            String  salt =  ClsEncriptar.generarSalt();

            String clave = ClsEncriptar.encriptaSHA256(this.txtClave.getText(), salt);

            //Registrar
            if ( error.isEmpty()) {

                salt =  ClsEncriptar.generarSalt();

                clave = ClsEncriptar.encriptaSHA256(this.txtClave.getText(), salt);
                //Usuario usuario = new Usuario();
                Usuario usuario = new Usuario(
                    this.txtCorreo.getText(),
                    clave,
                    salt,
                    this.txtUsername.getText(),
                    this.txtNombreC.getText()

                );

                if (UsuarioDAO.insertar(usuario)) {
                    this.dispose();
                };

            }else {
                JOptionPane.showMessageDialog(
                    null,
                    error,
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JLabel HopHorizontal1;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JPasswordField txtConfirmarClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
